const app=document.getElementById('app'); const S=window.NEGOTIATION_SCENARIOS; let st={};
document.getElementById('restart').onclick=()=>home();
const label=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()).replace(/\bTco\b/g,'TCO');
function btn(text,fn,cls='option'){const b=document.createElement('button');b.className=cls;b.textContent=text;b.onclick=fn;return b}
function set(html){app.innerHTML=html}
function home(){st={history:[],effects:[],submissionAttempted:false};set('<h2>Select a game</h2><p>Choose a scenario to begin.</p>');Object.entries(S).forEach(([k,g])=>app.appendChild(btn(`${g.game.id}. ${g.game.name}`,()=>selectGame(k))))}
function selectGame(k){st={...st,key:k,g:S[k],round:1,history:[],effects:[],submissionAttempted:false};const g=st.g;set(`<h2>${g.game.name}</h2><p>${g.brief}</p><div class="two"><div><h3>Customer position</h3><ul>${g.context.customer_position.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><h3>Supplier position</h3><ul>${g.context.supplier_position.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><p class="notice"><strong>Key question:</strong> ${g.context.key_question}</p><h3>Customer objective points</h3><p>${Object.entries(g.customer_objective_points).map(([k,v])=>`<span class="tag">${label(k)}: ${v}</span>`).join('')}</p><p>Supplier strategic score is determined by the hidden supplier profile. Both parties can score up to 30 economic points. Exact supplier priorities and economic scoring remain hidden until Results.</p><h3>Select supplier profile</h3>`);Object.entries(g.profiles).sort((a,b)=>a[1].display_order-b[1].display_order).forEach(([k,p])=>app.appendChild(btn(`${p.display_order}. ${label(k)} — ${p.description}`,()=>{st.profile=k;playRound()})))}
function has(req){return req.every(x=>st.history.some(h=>h.action===x)||st.effects.includes(x))}
function validity(action){const req=st.g.path_rules[action]||[];return {ok:has(req),reason:req.length?`Requires: ${req.map(label).join(', ')}`:''}}
function playRound(){if(st.round===2||st.round===4){supplierTurn();return} const r=st.g.rounds[`round_${st.round}`];set(`<h2>${st.g.game.name}</h2><h3>Round ${st.round}: Your decision</h3><div id="available"><h3>Available Actions</h3></div><div id="blocked"><h3>Blocked Actions</h3></div>`);const av=document.getElementById('available'),bl=document.getElementById('blocked');Object.entries(r.actions).forEach(([a,d])=>{const v=validity(a); if(v.ok)av.appendChild(btn(`${label(a)} — ${d}`,()=>customerAction(a))); else {const x=document.createElement('div');x.className='card blocked';x.innerHTML=`<strong>${label(a)}</strong>${d}<br><small>${v.reason}</small>`;bl.appendChild(x)}});if(!bl.querySelector('.card'))bl.innerHTML+='<p>None.</p>'}
function customerAction(a){st.history.push({round:st.round,actor:'Customer',action:a}); if(st.g.terminal&&st.g.terminal[a]){st.finalOutcome=st.g.terminal[a];return results()} if(st.round===3)st.round3=a;if(st.round===5){if(a==='commit') return finalizeCurrent(); if(a==='withdraw'){st.finalOutcome=st.key==='SAP_Transformation'?'continue_delay':'dispute';return results()} if(a==='change_direction')return chooseReplacement()} st.round++;playRound()}
function supplierTurn(){const rn=`round_${st.round}`,r=st.g.rounds[rn];let prefKey=rn;if(st.round===4&&st.round3==='negotiate_concession')prefKey='round_4_after_negotiate_concession';const prefs=st.g.preferences[st.profile][prefKey]||[];const valid=prefs.filter(a=>r.actions[a]&&validity(a).ok);const a=valid[0];if(!a){set('<p class="notice error">Undefined in scenario: no valid supplier action.</p>');return}st.history.push({round:st.round,actor:'Supplier',action:a});(st.g.action_effects[a]||[]).forEach(e=>{if(!st.effects.includes(e))st.effects.push(e)});set(`<h2>Round ${st.round}: Supplier action</h2><div class="card"><strong>${label(a)}</strong>${r.actions[a]}</div>`);app.appendChild(btn('Continue',()=>{st.round++;playRound()}))}
function finalizeCurrent(){let o=st.round3;if((st.g.intermediate_actions||[]).includes(o)){const supplier4=st.history.find(h=>h.round===4)?.action;o=st.g.outcome_resolution?.[o]?.[supplier4]}st.finalOutcome=o||'undefined';results()}
function chooseReplacement(){const r3=st.g.rounds.round_3.actions;set('<h2>Change Direction</h2><h3>Available Outcomes</h3>');Object.entries(r3).forEach(([a,d])=>{if((st.g.intermediate_actions||[]).includes(a))return;const v=validity(a);if(v.ok)app.appendChild(btn(`${label(a)} — ${d}`,()=>{st.history.push({round:5,actor:'Customer',action:`change_direction → ${a}`});st.finalOutcome=a;results()}));else app.innerHTML+=`<div class="card blocked"><strong>${label(a)}</strong>${v.reason}</div>`})}
function score(){const o=st.finalOutcome,ach=st.g.objective_achievement[o]||{customer:[],supplier:[]};const cs=ach.customer.reduce((n,x)=>n+(st.g.customer_objective_points[x]||0),0);const ss=ach.supplier.reduce((n,x)=>n+(st.g.profiles[st.profile].hidden_distribution[x]||0),0);const ce=st.g.customer_economic_scores[o]??0,se=st.g.supplier_economic_scores[o]??0;return {ach,cs,ss,ce,se,cf:cs+ce,sf:ss+se}}
function classify(cf,sf){if(cf>=60&&sf>=60)return'Mutual Gain';if(cf<=44&&sf<=44)return'Deadlock';if(cf>sf)return'Customer Advantage';if(sf>cf)return'Supplier Advantage';return'Undefined in scenario.'}
function results(){const q=score();st.q=q;set(`<h2>Negotiation Results</h2><p><strong>Final Outcome:</strong> ${label(st.finalOutcome)}</p><p><strong>Game Result:</strong> ${classify(q.cf,q.sf)}</p><div class="two"><div class="card"><h3>Customer</h3><p>Objectives: ${q.ach.customer.map(label).join(', ')||'None'}</p><p>Strategic: ${q.cs}</p><p>Economic: ${q.ce}</p><p class="score">${q.cf}/100</p></div><div class="card"><h3>Supplier</h3><p>Objectives: ${q.ach.supplier.map(label).join(', ')||'None'}</p><p>Strategic: ${q.ss}</p><p>Economic: ${q.se}</p><p class="score">${q.sf}/100</p></div></div><h3>Profile Reveal</h3><div class="card"><strong>${label(st.profile)}</strong>${st.g.profiles[st.profile].description}<p>${Object.entries(st.g.profiles[st.profile].hidden_distribution).map(([k,v])=>`<span class="tag">${label(k)}: ${v}</span>`).join('')}</p></div><h3>Course Concepts</h3><p>${st.g.course_concepts.map(x=>`<span class="tag">${label(x)}</span>`).join('')}</p><h3>Negotiation History</h3><table class="history"><tr><th>Round</th><th>Actor</th><th>Action</th></tr>${st.history.map(h=>`<tr><td>${h.round}</td><td>${h.actor}</td><td>${label(h.action)}</td></tr>`).join('')}</table><h3>Record score</h3><p>Would you like to record your score for this course?</p><div id="record"></div>`);const rec=document.getElementById('record');rec.appendChild(btn('YES',showSubmit));rec.appendChild(btn('NO',replay,'secondary'))}
function showSubmit(){const courseScore=Math.round(st.q.cf/10);set(`<h2>Record Score</h2><p>Assessment: <strong>${st.g.game.assessment_id}</strong></p><p>Negotiation score: <strong>${st.q.cf}/100</strong> | Course score to record: <strong>${courseScore}/10</strong></p><label>Student ID <input id="sid" placeholder="YYMMDD-##"></label><div id="msg"></div>`);app.appendChild(btn('Submit score',submitScore))}
async function submitScore(){const sid=document.getElementById('sid').value.trim(),msg=document.getElementById('msg');if(!/^\d{6}-\d{2}$/.test(sid)){msg.innerHTML='<p class="notice error">Student ID format is invalid.</p>';return}if(st.submissionAttempted){msg.innerHTML='<p class="notice error">This result has already been submitted, or the submission was already attempted.</p>';return}st.submissionAttempted=true;const url=window.PORTAL_CONFIG?.submitAssessmentUrl;if(!url){msg.innerHTML='<p class="notice error">Power Automate submission URL is not configured in config.js.</p>';return}try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({StudentID:sid,AssessmentID:st.g.game.assessment_id,Score:Math.round(st.q.cf/10)})});let body;try{body=await r.json()}catch{body=await r.text()}msg.innerHTML=`<p class="notice ${r.ok?'':'error'}">${r.ok?'Score successfully recorded.':(body?.message||body||`Submission failed (${r.status}).`)}</p>`}catch(e){msg.innerHTML=`<p class="notice error">${e.message}</p>`}}
function replay(){set('<h2>Replay Options</h2>');app.appendChild(btn('1. Replay same game with another profile',()=>selectGame(st.key)));app.appendChild(btn('2. Replay same profile with different decisions',()=>{const p=st.profile,k=st.key;st={history:[],effects:[],submissionAttempted:false,key:k,g:S[k],round:1,profile:p};playRound()}));app.appendChild(btn('3. Return to game selection',home));}
home();